language: node_js
node_js:
    - "7"
before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
script:
    - echo "Running test..."
    - npm run test
    - git branch -a
    # deploy to gihub pages
    - bash ./githubPageDeploy.sh
env:
    global:
        - ENCRYPTION_LABEL: 5f39565ca2eb
        - COMMIT_AUTHOR_EMAIL: andi.winata@hotmail.com
