sudo: required
dist: trusty
language: node_js
node_js:
    - "7"
# preparing chrome for karma
# http://blog.500tech.com/setting-up-travis-ci-to-run-tests-on-latest-google-chrome-version/
before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sudo apt-get update
    - sudo apt-get install -y libappindicator1 fonts-liberation
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - sudo dpkg -i google-chrome*.deb
script:
    - echo "Running test..."
    - npm run test
    - git branch -a
    # deploy to gihub pages
    - bash ./githubPageDeploy.sh
env:
    global:
        - ENCRYPTION_LABEL: 5f39565ca2eb
        - COMMIT_AUTHOR_EMAIL: andi.winata@hotmail.com
