/**
 * action types const
 */
export const SELECTED_TICKER_CHANGED = 'SELECTED_TICKER_CHANGED';
export const FETCH_TICKER_DATA_RECEIVED = 'FETCH_TICKER_DATA_RECEIVED';
export const SELECTED_DATE_CHANGED = 'SELECTED_DATE_CHANGED';