/**
 * action types const
 */
export const CHART_TYPE_CHANGED = 'CHART_TYPE_CHANGED';
export const SELECTED_TICKER_CHANGED = 'SELECTED_TICKER_CHANGED';
export const TICKER_DATA_RECEIVED = 'TICKER_DATA_RECEIVED';
export const SELECTED_DATE_CHANGED = 'SELECTED_DATE_CHANGED';